# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dj_Book_issued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dj_Book', models.CharField(max_length=50)),
                ('Dj_issued_on', models.DateField()),
                ('Dj_due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dj_Bookrelation',
            fields=[
                ('Dj_Book_isbn', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Dj_Book_name', models.CharField(max_length=50)),
                ('Dj_Author', models.CharField(max_length=50)),
                ('Dj_Publisher', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dj_book_issued',
            name='Dj_Book_isbn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Dj_Bookrelation'),
        ),
        migrations.AddField(
            model_name='dj_book_issued',
            name='Dj_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
