# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_dj_bookrelation_dj_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj_bookrelation',
            name='Dj_is_issued',
            field=models.BooleanField(default=False),
        ),
    ]
