# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_dj_bookrelation_dj_is_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj_book_issued',
            name='id',
        ),
        migrations.AlterField(
            model_name='dj_book_issued',
            name='Dj_Book_isbn',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.Dj_Bookrelation'),
        ),
    ]
